# -- 코드를 입력하세요
# SELECT A.CAR_ID, ROUND(AVG(A.DURATION), 1) AS AVERAGE_DURATION
# FROM (
#     SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ) A
# GROUP BY A.CAR_ID
# HAVING AVERAGE_DURATION >= 7
# ORDER BY AVERAGE_DURATION DESC,
#          A.CAR_ID
# ;

SELECT CAR_ID,
       ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC,
         CAR_ID DESC

;
