-- 코드를 작성해주세요
WITH FISH_LENGTH_ADJUSTED AS (
    SELECT ID, FISH_TYPE, COALESCE(LENGTH, 10) AS ADJUSTED_LENGTH, TIME
    FROM FISH_INFO
)

SELECT COUNT(B.FISH_TYPE) AS FISH_COUNT,
       MAX(B.LENGTH) AS MAX_LENGTH,
       B.FISH_TYPE
FROM FISH_INFO AS B, 
    (SELECT FISH_TYPE, AVG(ADJUSTED_LENGTH) AS AVG_LENGTH
     FROM FISH_LENGTH_ADJUSTED 
     GROUP BY FISH_TYPE ) AS A
WHERE B.FISH_TYPE = A.FISH_TYPE
AND A.AVG_LENGTH >= 33
GROUP BY B.FISH_TYPE
ORDER BY B.FISH_TYPE
;
